'''

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

'''

class Solution(object):
    def findTheDifference(self, s, t):
        result = 0
        print("t + s ->", s + t)
        for char in s + t:
            print("char ->", char)
            result ^= ord(char)
            print("result ->", result)
        print(chr(result))
        return chr(result)
     
              

solution = Solution()
s = "ae"
t = "aea"        
solution.findTheDifference(s, t)